stages:
  - build
  - test
  - quality

default:
  image: maven:3.8.1-jdk-11

build_job:
  inherit:
    default: true
  stage: build
  script:
    - mvn compile


test_job:
  inherit:
    default: true
    variables: true
  stage: test
  script:
    - mvn test
